"""
RED SHINOBI File Commands Module

Handles the /file and /save commands for file operations.
"""

import os
from typing import List

from rich.console import Console
from prompt_toolkit import PromptSession

from red_shinobi.core import brain
from red_shinobi.core.mcp_client import MCPManager
from red_shinobi.commands.model_cmds import get_available_models

console = Console()
THEME_COLOR = "red"
ACCENT_COLOR = "red"


async def execute(
    args: str,
    session: PromptSession,
    mcp_manager: MCPManager,
    session_history: list
) -> None:
    """
    Execute the /file command.
    Reads a local file and queries the first available model about it.
    
    Usage:
        /file <file_path> <query>
    
    Example:
        /file main.py Explain what this code does
    
    Args:
        args: The file path and query string
        session: The PromptSession instance
        mcp_manager: The MCPManager instance
        session_history: The conversation history list
    """
    parts = args.split(maxsplit=1)
    if len(parts) < 2:
        console.print(f"[{ACCENT_COLOR}][x] Usage: /file <path> <query>[/{ACCENT_COLOR}]")
        return
    
    file_path = parts[0]
    query = parts[1]
    
    if not os.path.exists(file_path):
        console.print(f"[{ACCENT_COLOR}][x] File not found: {file_path}[/{ACCENT_COLOR}]")
        return
    
    available_models = get_available_models()
    if not available_models:
        console.print(f"[{ACCENT_COLOR}][x] No models available. Configure API key first.[/{ACCENT_COLOR}]")
        return
    
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            file_content = f.read()
    except UnicodeDecodeError:
        try:
            with open(file_path, "r", encoding="latin-1") as f:
                file_content = f.read()
        except Exception as e:
            console.print(f"[{ACCENT_COLOR}][x] Error reading file: {e}[/{ACCENT_COLOR}]")
            return
    except Exception as e:
        console.print(f"[{ACCENT_COLOR}][x] Error reading file: {e}[/{ACCENT_COLOR}]")
        return
    
    # Truncate very large files
    max_chars = 50000
    if len(file_content) > max_chars:
        file_content = file_content[:max_chars] + f"\n\n[... truncated at {max_chars} characters ...]"
        console.print(f"[dim]Note: File truncated to {max_chars} characters[/dim]")
    
    first_model = available_models[0]
    console.print(f"\n[dim]Querying {first_model}...[/dim]\n")
    
    full_prompt = f"File: {file_path}\n\nContent:\n```\n{file_content}\n```\n\nQuery: {query}"
    
    try:
        response = await brain.chat_worker(
            model_name=first_model,
            prompt=full_prompt,
            mode="offline"
        )
        console.print(f"[{THEME_COLOR}]{first_model}:[/{THEME_COLOR}] {response}\n")
        session_history.append(f"**File Query ({file_path}):** {query}")
        session_history.append(f"**{first_model}:** {response}")
    except Exception as e:
        console.print(f"[{ACCENT_COLOR}][x] Error: {e}[/{ACCENT_COLOR}]")


async def save_execute(
    args: str,
    session: PromptSession,
    mcp_manager: MCPManager,
    session_history: list
) -> None:
    """
    Execute the /save command.
    Saves the session transcript to a markdown file.
    
    Usage:
        /save [filename]
    
    Args:
        args: Optional filename (defaults to transcript.md)
        session: The PromptSession instance
        mcp_manager: The MCPManager instance
        session_history: The conversation history list
    """
    if not session_history:
        console.print(f"[{THEME_COLOR}]No conversation to save[/{THEME_COLOR}]")
        return
    
    filename = args.strip() if args.strip() else "transcript.md"
    
    # Ensure .md extension
    if not filename.endswith(".md"):
        filename += ".md"
    
    try:
        with open(filename, "w", encoding="utf-8") as f:
            f.write("# RED SHINOBI Transcript\n\n")
            f.write("---\n\n")
            for entry in session_history:
                f.write(f"{entry}\n\n")
            f.write("---\n\n")
            f.write("*Generated by RED SHINOBI*\n")
        console.print(f"[green][ok] Saved to {filename}[/green]\n")
    except Exception as e:
        console.print(f"[{ACCENT_COLOR}][x] Error saving: {e}[/{ACCENT_COLOR}]")


async def read_execute(
    args: str,
    session: PromptSession,
    mcp_manager: MCPManager,
    session_history: list
) -> None:
    """
    Execute the /read command.
    Simply reads and displays a file's contents.
    
    Usage:
        /read <file_path>
    
    Args:
        args: The file path to read
        session: The PromptSession instance
        mcp_manager: The MCPManager instance
        session_history: The conversation history list
    """
    if not args:
        console.print(f"[{ACCENT_COLOR}][x] Usage: /read <path>[/{ACCENT_COLOR}]")
        return
    
    file_path = args.strip()
    
    if not os.path.exists(file_path):
        console.print(f"[{ACCENT_COLOR}][x] File not found: {file_path}[/{ACCENT_COLOR}]")
        return
    
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
    except UnicodeDecodeError:
        try:
            with open(file_path, "r", encoding="latin-1") as f:
                content = f.read()
        except Exception as e:
            console.print(f"[{ACCENT_COLOR}][x] Error reading file: {e}[/{ACCENT_COLOR}]")
            return
    except Exception as e:
        console.print(f"[{ACCENT_COLOR}][x] Error reading file: {e}[/{ACCENT_COLOR}]")
        return
    
    console.print(f"\n[{THEME_COLOR}]File: {file_path}[/{THEME_COLOR}]")
    console.print("[dim]" + "─" * 50 + "[/dim]")
    console.print(content)
    console.print("[dim]" + "─" * 50 + "[/dim]\n")
